[#75469] Pipeline test

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -2,6 +2,8 @@ trigger:
   branches:
     exclude:
       - '*'
+variables:
+  - group: integrationTestsVariables
 resources:
   containers:
     - container: db
@@ -13,105 +15,160 @@ resources:
         MYSQL_USER: mysql
         MYSQL_PASSWORD: mysql
         MYSQL_ROOT_PASSWORD: mysql
-    - container: elasticsearch
-      image: $(ELASTIC_SEARCH_IMAGE)
+      options: --health-cmd="mysqladmin ping -h localhost -u root --password=mysql || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
+
+    - container: opensearch
+      image: $(OPEN_SEARCH_IMAGE)
       ports:
         - "9200:9200"
-        - "9300:9300"
+        - "9600:9600"
       env:
         discovery.type: single-node
-        ES_JAVA_OPTS: -Xms1g -Xmx1g
-        cluster.routing.allocation.disk.threshold_enabled: false
-pool:
-  vmImage: ubuntu-latest
+        plugins.security.disabled: "true"
+        bootstrap.memory_lock: "false"
+        OPENSEARCH_JAVA_OPTS: "-Xms256m -Xmx256m"
+      options: --health-cmd="curl -f http://localhost:9200 || exit 1" --health-interval=15s --health-timeout=10s --health-retries=10
 
-services:
-  db: db
-  elasticsearch: elasticsearch
+jobs:
+  - job: MainJob
+    timeoutInMinutes: 180
 
-strategy:
-  matrix:
-    magento_2_4_6_php_8_1:
-      phpVersion: '8.3'
-      magentoVersion: '2.4.7-p3'
-      databaseName: 'magento_2_4_7_php_8_3'
-      composerOverride: '{}'
-      phpunitVersion: '^9'
+    pool:
+      vmImage: ubuntu-24.04
 
-steps:
+    services:
+      db: db
+      opensearch: opensearch
 
-  - script: |
-      sudo update-alternatives --set php /usr/bin/php$(phpVersion)
-      sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
-      sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
-      sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
-      sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
-      php -version
-    displayName: 'Use PHP Version $(phpVersion)'
+    strategy:
+      matrix:
+        magento_php:
+          phpVersion: $(PHP_VERSION)
+          magentoVersion: $(MAGENTO_VERSION)
+          databaseName: 'magento'
+          composerOverride: '{}'
+          phpunitVersion: $(PHP_UNIT_VERSION)
+          magentoDirectory: "/var/www/html"
 
-  - script: |
-      sudo apt-get install default-mysql-client
-      printf 'Waiting for MySQL database to accept connections'
-      until mysql --host 127.0.0.1 --user=mysql --password=mysql --execute "SHOW DATABASES"; do
-        printf '.'
-        sleep 1;
-      done;
-    displayName: 'Wait for Database to initialise'
+    steps:
 
-  - script: |
-      printf 'Waiting for elasticsearch to accept connections'
-      until curl -XGET '0.0.0.0:9200/'; do
-      printf '.'
-      sleep 1;
-      done;
-    displayName: 'Wait for Elasticsearch to initialise'
+      - script: |
+          sudo apt-get update
+          sudo apt-get install -y software-properties-common ca-certificates lsb-release apt-transport-https
+          sudo add-apt-repository ppa:ondrej/php -y
+          sudo apt-get update
+          sudo apt-get install -y php$(phpVersion) php$(phpVersion)-cli php$(phpVersion)-common php$(phpVersion)-mysql php$(phpVersion)-xml php$(phpVersion)-gd php$(phpVersion)-curl php$(phpVersion)-intl php$(phpVersion)-mbstring php$(phpVersion)-zip php$(phpVersion)-bcmath php$(phpVersion)-soap
+          sudo update-alternatives --set php /usr/bin/php$(phpVersion)
+          sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
+          sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
+          sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
+          sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
+          php -v
+        displayName: 'Install PHP $(phpVersion)'
 
-  - script: |
-      mkdir ../magento_$(magentoVersion)_$(phpVersion)
-      cd ../magento_$(magentoVersion)_$(phpVersion)
-      mkdir -p ../magento_$(magentoVersion)_$(phpVersion)/artifacts/lsretail/lsmag-two
-      cp -a /home/vsts/work/1/s/. ../magento_$(magentoVersion)_$(phpVersion)/artifacts/lsretail/lsmag-two/
-      composer init --name=lsretail/magento2 --type=project --require magento/product-community-edition:$(magentoVersion) --require $(composerName):$(composerVersion) --require-dev phpunit/phpunit:$(phpunitVersion) --repository '{"type": "composer", "url": "https://repo.magento.com/"}' --repository '{"type": "path", "url": "artifacts/*/*", "options": {"symlink": true}}' -s alpha -n
-      composer config use-include-path true
-      composer config --no-plugins allow-plugins true
-      php -r 'file_put_contents("composer.json", json_encode(array_merge_recursive(json_decode(file_get_contents("composer.json"), true), json_decode("{\"extra\": {\"magento-force\": \"override\"}, \"autoload\": {\"psr-4\": {\"Magento\\\\Framework\\\\\": \"lib/internal/Magento/Framework/\", \"Magento\\\\Setup\\\\\": \"setup/src/Magento/Setup/\", \"Magento\\\\\": \"app/code/Magento/\"}, \"psr-0\": {\"\": [\"app/code/\"]},\"files\": [\"app/etc/NonComposerComponentRegistration.php\"]}}", true), json_decode("$(composerOverride)", true)), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));'
-      echo '{"_comment": "These credentials were set up using some dummy Magento account", "http-basic": {"repo.magento.com": {"username": "$(MAGENTO_PUBLIC_KEY)", "password": "$(MAGENTO_PRIVATE_KEY)"}}}' > auth.json
-      composer install
-      composer require magento/magento-coding-standard --dev
-      find var vendor artifacts pub/static pub/media app/etc -type f -exec chmod u+w {} + && find var vendor artifacts pub/static pub/media app/etc -type d -exec chmod u+w {} + && chmod u+x bin/magento
-    displayName: 'Magento Code Preparation'
+      - script: |
+          # Install Xdebug for code coverage
+          sudo apt-get install -y php$(phpVersion)-xdebug
+          php -m | grep xdebug || echo "Xdebug not found"
+        displayName: 'Install Xdebug for code coverage'
+
+      - script: |
+          sudo apt-get install default-mysql-client
+          printf 'Waiting for MySQL database to accept connections'
+          until mysql --host 127.0.0.1 --user=mysql --password=mysql --execute "SHOW DATABASES"; do
+            printf '.'
+            sleep 1;
+          done;
+        displayName: 'Wait for Database to initialise'
+
+      - script: |
+          sudo apt-get update
+          sudo apt-get install -y apache2 libapache2-mod-php
+          sudo a2enmod rewrite
+          sudo service apache2 start
+          echo "Apache2 installed and started successfully."
+          AGENT_USER=$(whoami)
+          sudo sed -i "s/www-data/${AGENT_USER}/g" /etc/apache2/envvars
+          # Ensure the DocumentRoot directory has the correct permissions
+          sudo chown -R ${AGENT_USER}:${AGENT_USER} /var/www/html
+          sudo chmod -R 775 /var/www/html
+          sudo tee /etc/apache2/sites-available/magento.conf > /dev/null <<EOF
+              <VirtualHost *:80>
+                  ServerAdmin webmaster@localhost
+                  DocumentRoot /var/www/html
+                  ServerName mag.localhost.com
+                  DocumentRoot /var/www/html
+                  <Directory /var/www/html>
+                    Options Indexes FollowSymLinks MultiViews
+                    AllowOverride All
+                    Order allow,deny
+                    allow from all
+                  </Directory>
+                  ErrorLog \${APACHE_LOG_DIR}/error.log
+                  CustomLog \${APACHE_LOG_DIR}/access.log combined
+            </VirtualHost>
+          EOF
+              sudo ln -s /etc/apache2/sites-available/magento.conf /etc/apache2/sites-enabled/magento.conf
+              echo "127.0.0.1 mag.localhost.com" | sudo tee -a /etc/hosts
+              sudo systemctl restart apache2
+              echo "Magento Apache2 configuration applied."
+        displayName: 'Install and Start Apache2'
+
+      - script: |
+          cd $(magentoDirectory)
+          mkdir -p artifacts/lsretail/lsmag-two
+          cp -a /home/vsts/work/1/s/. $(magentoDirectory)/artifacts/lsretail/lsmag-two/
+          composer init --name=lsretail/magento2 --type=project --require magento/product-community-edition:$(magentoVersion) --require $(composerName):$(composerVersion) --require-dev phpunit/phpunit:$(phpunitVersion) --require-dev allure-framework/allure-phpunit:'^3.1' --repository '{"type": "composer", "url": "https://repo.magento.com/"}' --repository '{"type": "path", "url": "artifacts/*/*", "options": {"symlink": true}}' -s alpha -n
+          composer config use-include-path true
+          composer config --no-plugins allow-plugins true
+          php -r 'file_put_contents("composer.json", json_encode(array_merge_recursive(json_decode(file_get_contents("composer.json"), true), json_decode("{\"extra\": {\"magento-force\": \"override\"}, \"autoload\": {\"psr-4\": {\"Magento\\\\Framework\\\\\": \"lib/internal/Magento/Framework/\", \"Magento\\\\Setup\\\\\": \"setup/src/Magento/Setup/\", \"Magento\\\\\": \"app/code/Magento/\"}, \"psr-0\": {\"\": [\"app/code/\"]},\"files\": [\"app/etc/NonComposerComponentRegistration.php\"]}}", true), json_decode("$(composerOverride)", true)), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));'
+          echo '{"_comment": "These credentials were set up using some dummy Magento account", "http-basic": {"repo.magento.com": {"username": "$(MAGENTO_PUBLIC_KEY)", "password": "$(MAGENTO_PRIVATE_KEY)"}}}' > auth.json
+          composer install
+          composer require magento/magento-coding-standard --dev
+          composer require lusitanian/oauth --dev
+          cat composer.json
+          cat composer.lock
+          find var vendor artifacts pub/static pub/media app/etc -type f -exec chmod u+w {} + && find var vendor artifacts pub/static pub/media app/etc -type d -exec chmod u+w {} + && chmod u+x bin/magento
+        displayName: 'Magento Code Preparation'
 
   - script: |
       cd ../magento_$(magentoVersion)_$(phpVersion)
       ./vendor/bin/phpcs --standard=vendor/magento/magento-coding-standard/Magento2/ruleset.xml --ignore=artifacts/lsretail/lsmag-two/dev --warning-severity=8 --extensions=php artifacts/lsretail/
     displayName: 'Magento2 Coding Standards Validation'
+
   - script: |
       telnet 127.0.0.1 3306
       mysql --host 127.0.0.1 --user=root --password=mysql -e "CREATE DATABASE $(databaseName)"
     displayName: 'Magento Database Creation'
 
-  - script: ../magento_$(magentoVersion)_$(phpVersion)/bin/magento setup:install --base-url=http://magento.$(magentoVersion).$(phpVersion).local/ --backend-frontname=admin --db-host=127.0.0.1 --db-name=$(databaseName) --db-user=root --db-password=mysql --admin-firstname=John --admin-lastname=Doe --admin-email=john.doe@orba.co --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=127.0.0.1 --elasticsearch-port=9200
+  - script: |
+      cd $(magentoDirectory)
+      php bin/magento setup:install --base-url=http://mag.localhost.com/ --backend-frontname=admin --db-host=127.0.0.1 --db-name=$(databaseName) --db-user=root --db-password=mysql --admin-firstname=John --admin-lastname=Doe --admin-email=john.doe@orba.co --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=opensearch --opensearch-host=127.0.0.1 --opensearch-port=9200
     displayName: 'Magento Installation Testing'
 
   - script: |
-      php -d memory_limit=-1 ../magento_$(magentoVersion)_$(phpVersion)/bin/magento deploy:mode:set developer -vvv || cat var/log/exception.log || cat var/log/system.log
-    displayName: 'Magento set developer mode'
+      cd $(magentoDirectory)
+      php -d memory_limit=-1 bin/magento deploy:mode:set developer
+    displayName: 'Magento developer mode Testing'
 
   - script: |
-      php -d memory_limit=-1 ../magento_$(magentoVersion)_$(phpVersion)/bin/magento setup:upgrade -vvv || cat var/log/exception.log
+      cd $(magentoDirectory)
+      php -d memory_limit=-1 bin/magento setup:upgrade -vvv || cat var/log/exception.log
     displayName: 'Magento setup upgrade'
 
   - script: |
-      php -d memory_limit=-1 ../magento_$(magentoVersion)_$(phpVersion)/bin/magento setup:di:compile -vvv || cat var/log/exception.log
+      cd $(magentoDirectory)
+      php -d memory_limit=-1 bin/magento setup:di:compile -vvv || cat var/log/exception.log
     displayName: 'Magento setup di compile'
 
   - script: |
-      php -d memory_limit=-1 ../magento_$(magentoVersion)_$(phpVersion)/bin/magento setup:static-content:deploy -f -vvv || cat var/log/exception.log
+      cd $(magentoDirectory)
+      php -d memory_limit=-1 bin/magento setup:static-content:deploy -f -vvv || cat var/log/exception.log
     displayName: 'Magento static content deploy'
 
   - script: |
-      cd ../magento_$(magentoVersion)_$(phpVersion)
-      cp ../magento_$(magentoVersion)_$(phpVersion)/artifacts/lsretail/lsmag-two/dev/tests/unit/azure-pipelines-phpunit.xml ../magento_$(magentoVersion)_$(phpVersion)/dev/tests/unit/
+      cd $(magentoDirectory)
+      cp artifacts/lsretail/lsmag-two/dev/tests/unit/azure-pipelines-phpunit.xml dev/tests/unit/
       ./vendor/bin/phpunit -c dev/tests/unit/azure-pipelines-phpunit.xml --log-junit ../magento_$(magentoVersion)_$(phpVersion)/$(System.DefaultWorkingDirectory)/junit-report_$(magentoVersion)_$(phpVersion).xml
     displayName: 'Ls Retail Modules Unit Tests Validation'
 
